### ISSUE TITLE
Scim 

### ISSUE THREAD

**Issue by sdv-mini-dev-1** [simpleidserver/SimpleIdServer#18]
Hi,
cool project!
Do you have some samples for scim endpoints **consuming using basic authentication**? 
Example

- Create: POST https://example.com/{v}/{resource}
- Read: GET https://example.com/{v}/{resource}/{id}
- Search: GET https://example.com/{v}/{resource}?ﬁlter={attribute}{op}{value}&sortBy={attributeName}&sortOrder={ascending|descending}

**Comment by simpleidserver** [comment]
Hello,

Except from the specflow tests "https://github.com/simpleidserver/SimpleIdServer/blob/master/tests/SimpleIdServer.Scim.Host.Acceptance.Tests/Features/Users.feature", we don't have samples projects which consume the SCIM endpoints.
In near future we are going to put some samples projects and add some documentations about SCIM.

Kind regards.

**Comment by sdv-mini-dev-1** [comment]
Is bearer token authentication the only option? 
What about the basic authentication?

**Comment by simpleidserver** [comment]
It's up to the **developer** to configure the **authentication** strategy in the Startup.cs class.
As you can see in the "Startup.cs" (https://github.com/simpleidserver/SimpleIdServer/blob/master/src/Scim/SimpleIdServer.Scim.Startup/Startup.cs) class the bearer token authentication is used, 
but you can also configure the "basic authentication" like this : https://jasonwatmore.com/post/2018/09/08/aspnet-core-21-basic-authentication-tutorial-with-example-api.

**Note** : The usage of basic authentication should be avoided, due to its use of a single factor that is based upon a relatively static, symmetric secret.
