### ISSUE TITLE
Persistence howto

### ISSUE THREAD

**Issue by bzuidgeest** [simpleidserver/SimpleIdServer#20]
Hello,

I recently downloaded your project to try and see if I could use it to set-up a scrim server. Using the test code and startup code in the repository as a guide I was able to setup my own project with the nuget package. I can call into the schema endpoint and that is all fine. It seems to be a very nice package.

What I am missing is any instruction on how to switch from the default inMemory persistence model to a sql server database. In the repository there is "SimpleIdServer.Scim.Persistence.EF", but there seems to be no nuget package for that. It seems to me that I am required to provide my own equivalent of that project using "SimpleIdServer.Scim.Persistence.EF" as a base. Is this assumption correct or am I missing something?

Any instruction on the subject of persistence is appreciated.

**Comment by simpleidserver** [comment]
Hello,

The nuget package "SimpleIdServer.Scim.Persistence.EF" has not been published because it's has not been tested yet.

We are going to test it and publish it as soon as possible, meanwhile you can use the library "SimpleIdServer.Scim.Persistence.EF" and follow the steps below :

1. Create an empty project.
2. Install the SCIM nuget package.
3. Reference the library "SimpleIdServer.Scim.Persistence.EF".
4. Install the nuget package "Microsoft.EntityFrameworkCore.SqlServer" and configure the connection string in the Startup / Program file.

**Comment by simpleidserver** [comment]
The nuget package has been published into the Nuget feed "https://www.nuget.org/packages/SimpleIdServer.Scim.Persistence.EF".

You can follow the tutorial "https://simpleidserver.readthedocs.io/en/latest/persistence/entityframework-scim.html" to configure and install the package.

Sample project : https://github.com/simpleidserver/SimpleIdServer/tree/master/src/Scim/SimpleIdServer.Scim.SqlServer.Startup
