### ISSUE TITLE
'SimpleIdServerOpenIDBuilder' does not contain a definition for 'AddLoginPasswordAuthentication'

### ISSUE THREAD

**Issue by auxon** [simpleidserver/SimpleIdServer#202]
Trying to following the docs I get this error compiling as the extension method appears to be missing from the SimpleIdServer.OpenID nuget package build.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SimpleIdServerOpenIDBuilder' does not contain a definition for 'AddLoginPasswordAuthentication' and no accessible extension method 'AddLoginPasswordAuthentication' accepting a first argument of type 'SimpleIdServerOpenIDBuilder' could be found (are you missing a using directive or an assembly reference?)	ScimHost	C:\source\connect\ScimHost\OpenIdStartup.cs	35	Active

**Comment by simpleidserver** [comment]
Hello,

Indeed the deployed documentation is not up to date. We are currently working on an another documentation (see the branch "release/2.0.1) in order to facilitate the usage of SimpleIdServer.

The Nuget package "SimpleIdServer.UI.Authenticate.LoginPassword.Bootstrap4" should also be installed into your OpenId project, in order to have "Login & Password" authentication active in your solution.

**Comment by auxon** [comment]
Thanks for the quick response.  Good to know.
