### ISSUE TITLE
[SCIM] 2.0.6 regression - when querying users with `emails` attribute only fails

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#257]
I use SCIM with EF5.

When I try to query the users endpoint to only get emails, an exception is thrown.

Steps to reproduce:
1. Insert users 
2. Query users endpoint, while requesting the `emails` only.

This results in an exception with the following message.

```
The expression 'r.Children' is invalid inside an 'Include' operation, since it does not represent a property access: 't => t.MyProperty'. To target navigations declared on derived types, use casting ('t => ((Derived)t).MyProperty') or the 'as' operator ('t => (t as Derived).MyProperty'). Collection navigation access can be filtered by composing Where, OrderBy(Descending), ThenBy(Descending), Skip or Take operations. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.
```

**Comment by simpleidserver** [comment]
Indeed there is a regression.
The issue should be fixed in the branch "release/2.0.7" & has been tested with DOTNET5 & DOTNET6.

In the new implementation "SCIMRepresentationCommandRepository" is using an another DBContext with different configuration.

Can-you please check if everything is working for you  by using the branch "release/2.0.7".
