### ISSUE TITLE
[SCIM] 2.0.10 regression with Enterprise Users

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#287]
The response to POST\GET a user with enterprise properties does not contain the values of enterprise users.

For example, a POST to create a user with a department, does not return the department of the user.
Same for a GET operation.

**Comment by simpleidserver** [comment]
Hello,

In the version 2.0.10, a new property `MergeExtensionAttributes`  has been added into the SCIMHostOptions.
By default the value is set to **false** and entreprise attributes are returned in the `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` namespace. This change has been made in order to match the RFC.

However, this behavior can be disabled by setting the property  value `MergeExensionAttributes` to `true`. 
Therefore when the property is true then the department is returned as a CORE attribute.

Kind regards,

SID
