### ISSUE TITLE
[SCIM] attributes with null representation id when using EF6

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#300]
Hello,

When trying to upgrade to EF6 I encountered a situation where attributes are saved in the DB with NULL `representationId`.

Ways to reproduce - 
1. POST a user
2. POST a group with the user in it
3. PUT the group to contain no members

Please tell me if you have any issues with reproducing.

Many thanks 
Dan

**Comment by simpleidserver** [comment]
Hello,

The changes has been rolled back in the master branch.
Now, when sub-attributes (email.value, groups.value) are removed from a representation, then they are correctly deleted from the table SCIMRepresentationAttributeLst.
However, **orphan attributes** are still present ("emails" or "groups") even their entity states are set to "DELETED" inside the change tracker.

I need more time to make more investigation in the EFCore6, trying to understand why there is a difference between EFCORE5 and EFCORE6.
When I will find the root cause then both tickets #300 & #297 will be fixed (probably after my holidays ~12august)
Meanwhile you can use the following Pre-Relase Version or use the version 5 `SimpleIdServer.Scim.Persistence.EF`

https://www.myget.org/feed/advance-ict/package/nuget/SimpleIdServer.Scim.Persistence.EFNet6/2.0.12-ci-00314

KR,

Sid

**Comment by simpleidserver** [comment]
Hello,

After some time, I found a Hack to remove orphans from representations.
Even if the EntityState property is set to "Removed", the attribute was not removed from the `FlatAttributes` collection.
The hack remove the attribute from this collection.

The changes are present in the branch "release/v2.0.14".

KR,

Sid

**Comment by danflomin** [comment]
At the moment things looks steady with EF6 :)
