### ISSUE TITLE
Cannot add a new users schema extension through "UserSchema.json"

### ISSUE THREAD

**Issue by MoamenShehata** [simpleidserver/SimpleIdServer#326]
Hello,
I got back a 400 ERROR while sending a POST request to "/Users" with the following request body  
`{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User",
        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    ],
    "externalId": "external",
    "userName": "name@name.com",
    "meta": {
        "resourceType": "User"
    },
}`

this is because this schema "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" was not defined in the "UserSchema.json" file.
So, once I added it manually to the database table "SCIMSchemaExtension" it worked just fine.

So, can you please tell me how can I fix this?

Thanks a lot

**Comment by simpleidserver** [comment]
Hello,

The schema "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" is defined in its own file, it can be downloaded here : https://raw.githubusercontent.com/simpleidserver/SimpleIdServer/master/src/Scim/SimpleIdServer.Scim.Startup/Schemas/EnterpriseUserSchema.json

**PART 1 : Configure an extension schema**

To configure an extension schema in your project, follow those steps:
* Download both JSON files `User` and `EntrepriseUser` and add them into your project.
* Edit the `Startup.cs` class and extract the User Schema from the file:

```
var userSchema = SCIMSchemaExtractor.Extract(Path.Combine(basePath, "UserSchema.json"), SCIMResourceTypes.User, true);
```

* Extract the extension schema from the file:

```
 var entrepriseUser = SCIMSchemaExtractor.Extract(Path.Combine(basePath, "EnterpriseUser.json"), SCIMResourceTypes.User);
```

* Add to the User Schema a reference to the extension schema:

```
userSchema.SchemaExtensions.Add(new SCIMSchemaExtension
{
    Id = Guid.NewGuid().ToString(),
    Schema = "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
});
```
* Initialize the DBContext and add both schemas : 

``` 
using (var scope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
    using (var context = scope.ServiceProvider.GetService<SCIMDbContext>())
    {
		context.Database.Migrate();
		var basePath = Path.Combine(_webHostEnvironment.ContentRootPath, "Schemas");
		var userSchema = SCIMSchemaExtractor.Extract(Path.Combine(basePath, "UserSchema.json"), SCIMResourceTypes.User, true);
		var entrepriseUser = SCIMSchemaExtractor.Extract(Path.Combine(basePath, "EnterpriseUser.json"), SCIMResourceTypes.User);
        userSchema.SchemaExtensions.Add(new SCIMSchemaExtension
		{
			Id = Guid.NewGuid().ToString(),
			Schema = "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
		});   
		if (!context.SCIMSchemaLst.Any())
        {
            context.SCIMSchemaLst.Add(userSchema);
            context.SCIMSchemaLst.Add(entrepriseUser);
        }
		
		
        context.SaveChanges();
	}
}
``` 

A full working version can be found here : https://github.com/simpleidserver/SimpleIdServer/tree/master/src/Scim/dotnet6/SimpleIdServer.Scim.SqlServer.Startup

**PART 2: Create a user (HTTP REQUEST)**

Your HTTP request is not correct because the `name` is missing.
According to the `User` schema, this attribute is required.
A valid HTTP request is : 

```
{
	"schemas": [ "urn:ietf:params:scim:schemas:core:2.0:User", "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User" ],
	"externalId": "external", 
	"userName": "name@name.com",
	  "name": {
	    "formatted": "Andrew Ryan",
	    "familyName": "Ryan",
	    "givenName": "Andrew"
	  }
}
``` 

KR,

SID

**Comment by MoamenShehata** [comment]
Hello,

Thank you so much for the detailed answer really much appreciated.

Can I ask you please if there is a full documentation that I can refer to?

Kind Regards

**Comment by simpleidserver** [comment]
Unfortunately this part is not yet explained in the documentation. 
For now, you can play with the different samples project present here : https://github.com/simpleidserver/SimpleIdServer/tree/master/samples

* UseSCIMSwagger : the project is configured to use Swagger
* UseSCIMSqlServer : the project is configured to use an SQLServer database.
* UseSCIMMongoDB : the project is configured to use a MongoDB.
