### ISSUE TITLE
SCIM - Listen for events

### ISSUE THREAD

**Issue by Thijmen** [simpleidserver/SimpleIdServer#468]
Hi,

I created a SCIM server with the following:
```
dotnet new scimef -n ScimEF --connectionString "Data Source=.;Initial Catalog=SCIM;Integrated Security=True;TrustServerCertificate=True"
```

Now, how can I listen for events, e.g. user added/deleted? Or maybe I misunderstand how the scimef project should be used.

Thanks for your contributions, the API works fine!

**Comment by Thijmen** [comment]
Hello SID,

Thanks! I now can listen to the event. Is there any way to map a resource to a User or a Group? What would you recommend?

**Comment by simpleidserver** [comment]
Because, the form of a representation is defined by a SCIM Schema, we made the choice to return the representation as a JSON object.
It is possible to extract the user like this :

```
public Task Consume(ConsumeContext<RepresentationAddedEvent> context)
{
    switch(context.Message.ResourceType)
    {
        case SCIMConstants.ResourceTypes.ScimUser:
            ExtractUser(context.Message.Representation);
            break;
        case SCIMConstants.ResourceTypes.ScimGroup:

            break;
    }

    return Task.CompletedTask;

    User ExtractUser(JObject jObj)
    {
        return new User
        {
            Id = context.Message.Id,
            UserName = jObj["userName"].ToString()
        };
    }
}

private class User
{
    public string Id { get; set; }
    public string UserName { get; set; }
}
```

All the user properties are defined in the file `Schemas\UserSchema.json`.

**Comment by Thijmen** [comment]
Awesome, thanks for the fast reply! And say we wanted to add a secret token, to provision from Azure AD, how would we be able to achieve that?

**Comment by Thijmen** [comment]
Cheers, that seems to work flawless! One other question, how can I implement my own DbContext, to have a different schema other than DBO?

**Comment by simpleidserver** [comment]
Hello,

Indeed, at the moment it is not easy to override the default schema.
We made some modifications in the release **3.0.3** to support this small feature.

The default schema can easily be changed like this :

1. Use the template to install a local version of SCIM.
2. Remove all the migrations scripts (files present in the `Migrations` folder) and drop your local database.
3. Edit the `Startup.cs` file and replace the `AddScimStoreEF` by the following code. The property `DefaultSchema` contains the name of your schema.

```
 services.AddScimStoreEF(options =>
{
	options.UseSqlServer(Configuration.GetConnectionString("db"), o =>
      {
      	o.MigrationsAssembly(migrationsAssembly);
            o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery);
      });
}, options =>
{
	options.DefaultSchema = "scim";
}); 
```
4. Launch the application.

All the tables should be created under the `scim` schema.

IMPORTANT NOTE : Since the version 3.0.3, SCIM is configured by default to use the API KEY configuration.
In order to access to the different endpoints you must pass a valid API KEY into the request (Authorization Bearer APIKEY). 
Those keys are configured in the `appsettings.json` file.

| Key |
| --- |
| ba521b3b-02f7-4a37-b03c-58f713bf88e7 |
| 1595a72a-2804-495d-8a8a-2c861e7a736a |

During the configuration of your Azure Active Directory provisioning, you can use one of them.

**Comment by simpleidserver** [comment]
The version 3.0.3 is already released and there is no breaking change :)

**Comment by Thijmen** [comment]
Cool, thanks a lot! Awesome work, keep it up!
