### ISSUE TITLE
UI - Secure the website

### ISSUE THREAD

**Issue by simpleidserver** [simpleidserver/SimpleIdServer#485]

**Comment by lechediaz** [comment]
Hello @simpleidserver ,

I have a snag while solving this issue but at the time of logging out, you will see, in line 229 of the `Validate` method of the file `s srcIdServer.IdServer.CheckSessionController.cs` the JWT audiences are being compared with the absolute path of the host where SimpleIdServer is published, but the truth is that to interact with the server it is necessary to use a `Realm`, then adding the comparison like this:

```
if (!extractionResult.Jwt.Audiences.Contains($"{Request.GetAbsoluteUriWithVirtualPath()}/{realm}"))
```
It works correctly, but then I get the following error: "the alg used to sign the id_token_hint is invalid", but there I don't know what to do since the token was generated by the SimpleIdServer itself.

Can you check my https://github.com/lechediaz/SimpleIdServer/tree/issue-485 branch for a moment please?

the key files are:

- srcSimpleIdServer.IdServer.Website.ServiceCollectionExtensions.cs
- srcIdServer.IdServer.Website.IdServer.WebsiteMiddleware.cs
- srclectionExtensions.cs srclectionExtensions.cs srclectionExtensions.razor.cs
- srcServer.IdServer.IdServer.Website.Startup.Program.cs

You need to manually add the redirection URL after logout to the "SIDS-manager" client to "http://localhost:5002/signout-callback-oidc"

I would appreciate any comments or suggestions to complete this issue.

**Comment by simpleidserver** [comment]
Hello, 

First thank you for your feedback. I m going to take a look to this issue next tuesday (02 may)

Kr,

Sid

**Comment by simpleidserver** [comment]
Hello,

You'll find in attachment the PATCH file, please download it and execute this command to apply the PATCH:

```
git apply 0001-Ticket-485-Fix-logout-profile.patch
```

I made the following changes:
* Use controller instead of Middleware, contains one Logout operation.
* Fix logic used to logout a user.

I suggest to logout from the Cookies scheme and not from OIDC because there is no iframe in the website to check if the session is still valid. For more information please refer to this documentation : https://curity.io/resources/learn/openid-connect-logout/

The code should look like to something like this : 

```
            return SignOut(new AuthenticationProperties
            {
                RedirectUri = Url.Content("~/")
            }, "Cookies");
```

KR,

SID

**Comment by lechediaz** [comment]
Thank you very much, I will check it out later.

**Comment by lechediaz** [comment]
Hello friend, I wanted to tell you that I tested it and it works perfectly. I learned that you can work perfectly with controllers in a project with Blazor, thank you very much for the support.

I will send the PR with these changes you sent me.

Best regards.
