### ISSUE TITLE
SCIM usage documentation

### ISSUE THREAD

**Issue by boris-meerovich-sp** [simpleidserver/SimpleIdServer#50]
Hi,
Do have any plans to add more content to the SCIM documentation (https://simpleidserver.readthedocs.io/en/latest/intro/getting-started-with-scim.html)?

I'm using the SCIM server for several weeks to make POC of migration our SCIM to .net core with SimpleIdServer and only one way that I found to discover stuff, is by debugging the original source code.
It takes time...

I'm looking for:
- documentation for adding custom resources (the samples are very basic)
- where is the correct point in the code to get business objects from our DB and convert it to SCIM objects. I made it by implementing ISCIMRepresentationQueryRepository interface.
- how do you suggest convert business objects to SCIM representations? I made it by AutoMapper where I map each property to SCIM property.
- What the purposes of : ISCIMSchemaQueryRepository, IPatchRepresentationCommandHandler, IReplaceRepresentationCommandHandler, IDeleteRepresentationCommandHandler, IAddRepresentationCommandHandler
- We have 8 different end-points in our SCIM server and some objects are persists in other objects. What the correct way to re-use the same schemas in the object?

Maybe you have any flow chart to demonstrate the pipeline of the request and response?
P.S. We're migrating from this project: https://github.com/PowerDMS/Owin.Scim

Please, advise,

**Comment by simpleidserver** [comment]
**Question :  documentation for adding custom resources (the samples are very basic) :**

A custom SCIM resource can be added in three steps :

1. Use the fluent API to build the SCIM schema. For example, a resource with two string parameters can be built like this:

```
var customSchema = Builder.SCIMSchemaBuilder.Create("urn:customresource", "CustomResources", "CustomResources")
.AddStringAttribute("name")
.AddStringAttribute("lastname")
.Build();
```

The *Create* method has three parameters :
* *id* : The unique URI of the schema.
* *name* : The schema's human-readable name. 
* *resourceType* : Type of resource. This parameter is used to link several SCIM schemas to one resource type.  For example, in the project *SimpleIdServer.Scim.SqlServer.Startup* there is a *User* resource with two SCIM schemas : *urn:ietf:params:scim:schemas:extension:eid:2.0:User* and *urn:ietf:params:scim:schemas:core:2.0:User*.


2. Insert the new SCIM schema into the table SCIMSchema. In the *Configure* method of the file *Startup.cs* add the following instruction to register the Schema :

```
using (var scope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
	var context = scope.ServiceProvider.GetService<SCIMDbContext>())
	{
		context.SCIMSchemaLst.Add(customSchema.ToModel());
		context.SaveChanges();
	}
}

```
3. Add a controller for the new type of resource. The name of the resource type must be passed into the BaseApiController constructor.

```
    [Route("CustomResources")]
    public class CustomResourcesController : BaseApiController
    {
        public CustomResourcesController(IAddRepresentationCommandHandler addRepresentationCommandHandler, 
			IDeleteRepresentationCommandHandler deleteRepresentationCommandHandler, 
			IReplaceRepresentationCommandHandler replaceRepresentationCommandHandler, 
			IPatchRepresentationCommandHandler patchRepresentationCommandHandler, 
			ISCIMRepresentationQueryRepository scimRepresentationQueryRepository, 
			ISCIMSchemaQueryRepository scimSchemaQueryRepository, 
			IAttributeReferenceEnricher attributeReferenceEnricher, 
			IOptionsMonitor<SCIMHostOptions> options, 
			ILogger<CustomResourcesController> logger) : base("CustomResources", addRepresentationCommandHandler, deleteRepresentationCommandHandler, replaceRepresentationCommandHandler, patchRepresentationCommandHandler, scimRepresentationQueryRepository, scimSchemaQueryRepository, attributeReferenceEnricher, options, logger)
        {
        }
    }
```
	
4. Once everything is setup you can start playing with the SCIM endpoints :

http://localhost/CustomResources : Get all resources.
http://localhost/CustomResources?filter=name eq firstName : Filter resources. 

**Question : where is the correct point in the code to get business objects from our DB and convert it to SCIM objects. I made it by implementing ISCIMRepresentationQueryRepository interface :_** 

To convert your business objects into SCIM objects, there are two solutions :

1. If you want to use your DB instead of the DB provided by SimpleIdServer.Scim, then you need a library which implements all the repositories : ISCIMAttributeMappingQueryRepository, ISCIMRepresentationCommandRepository, ISCIMRepresentationQueryRepository, ISCIMSchemaCommandRepository, ISCIMSchemaQueryRepository.

**Advantage** : no migrations scripts
**Disadvantage** : Can be difficult to rewrite the EFSCIMExpressionLinqExtensions, this class is used to convert SCIM filter into LINQ expression tree.

2. Migrate from the Owin.Scim database to the new one SimpleIdServer.Scim :

- Use SQL migration scripts (ETL).

**Advantage** : most performant approach.
**Disadvantage** : you must know the database structure.

- Create a console application which fetches SCIM representations from the old database and call the BULK API operation to insert new SCIM representations.

**Advantage** : easiest approach.
**Disadvantage** : less performant approach.

**Question : how do you suggest convert business objects to SCIM representations? I made it by AutoMapper where I map each property to SCIM property **

see the answer above.

** Question : What the purposes of : ISCIMSchemaQueryRepository, IPatchRepresentationCommandHandler, IReplaceRepresentationCommandHandler, IDeleteRepresentationCommandHandler, IAddRepresentationCommandHandler**

**ISCIMSchemaQueryRepository** : Get SCIM schemas.
**IPathRepresentationCommandHandler** : Apply patch operations on SCIM representations : https://tools.ietf.org/html/rfc7644#section-3.5.2
**IDeleteRepresentationCommandHandler** : Remove the SCIM representation.
**IAddRepresentationCommandHandler** : Add a SCIM representation.

There are two concepts in SimpleIdServer.Scim project : 

1. The SCIM schema defines the structure of a SCIM resource.
2. SCIM representation = SCIM resource = record

**Question : We have 8 different end-points in our SCIM server and some objects are persists in other objects. What the correct way to re-use the same schemas in the object?**

It's possible to use the same SCIM schema by adding an extension schema. 
The following code configures a shared SCIM schema :

```
var sharedSchema = Builder.SCIMSchemaBuilder.Create("urn:sharedresource", "SharedResource", null)
.AddStringAttribute("shared")
.Build();
var userSchema = Builder.SCIMSchemaBuilder.Create("urn:user", "UserResource", "Users")
.AddStringAttribute("firstName")
.Build();
var groupSchema = Builder.SCIMSchemaBuilder.Create("urn:group", "GroupResource", "Groups")
.AddStringAttribute("firstName")
.Build();
userSchema.SchemaExtensions.Add(new SCIMSchemaExtension
{
    Id = Guid.NewGuid().ToString(),
    Schema = sharedSchema.Id
});
groupSchema.SchemaExtensions.Add(new SCIMSchemaExtension
{
    Id = Guid.NewGuid().ToString(),
    Schema = sharedSchema.Id
});
```

**Note : we can help you in implementing a SimpleIdServer.Scim.Persistence.OwinScim.EF library to use the Owin.Scim database.**

**Comment by boris-meerovich-sp** [comment]
Thanks for the detailed answers!!!
Since the DB will remain still the same DB and we already have a code to convert the SCIM filter, I feel that we're on the right way :).
