### ISSUE TITLE
[SCIM] publish to masstransit fails

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#554]
Hello, how are you?

I'm having issues with publishing events related to data with nested groups.

I'm getting the following error when trying to publish the event.

```
A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Message.Attribute.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.FlatAttributes.Representation.ExternalId.
```

Do you think you know what the root cause of this?
It was introduced when I upgraded from 2.0.25 to 4.0.2.

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello :)

I believe you received this exception because the SCIMRepresentation object is being passed as a parameter to MassTransit, and it is not possible to serialize this object due to the presence of a reference to the Parent in the SCIMRepresentationAttribute attribute.

In the SCIM Server implementation, the SCIMRepresentation is not directly passed to MassTransit. Instead, it is serialized into JSON using the following code before being passed to MassTransit:

```
var content = newRepresentation.ToResponse(location, false);
```

Could you please check if you can serialize the Representation before passing the result to MassTransit?

KR,

SID

**Comment by danflomin** [comment]
Hello

I'm sorry for the incomplete information.

The exception was of type `System.Runtime.Serialization.SerializationException`

```
System.Runtime.Serialization.SerializationException: Failed to serialize message
  File "/_/src/MassTransit/Serialization/SystemTextJsonMessageBody.cs", line 56, col 17, in byte[] SystemTextJsonMessageBody<TMessage>.GetBytes()
  File "/_/src/MassTransit/InMemoryTransport/InMemoryTransport/InMemorySendTransportContext.cs", line 58, col 13, in Task InMemorySendTransportContext.Send<T>(PipeContext transportContext, SendContext<T> sendContext)
  ?, in async Task SendPipe<T>.Send(TContext context)
```


Kind regards 
Dan

**Comment by simpleidserver** [comment]
Thank you for raising the exception, but it should not occur in the SCIM Server. This is because the SCIMRepresentation is directly passed to MassTransit, but before sending it to MassTransit, it is first serialized into JSON.

Have you added custom code that sends the SCIMRepresentation instead of the JSON object?

Please refer to my previous message for more information :)

**Comment by danflomin** [comment]
No I did not :(
I wonder if it happens due to a corruption in the data (maybe a circular memberships of groups?).

I guess that prior to publishing the event, it will be preferable to not add the representation that is attached to the attribute as well (it happens only for reference events).

WDYT?

**Comment by danflomin** [comment]
Also, can you please add my account as a contributor? I'd like to submit a pull request

**Comment by simpleidserver** [comment]
Oops, my bad ! 

The exception is being thrown because the SCIMRepresentationAttribute is passed as a parameter into the events RepresentationRefAttributeAddedEvent, RepresentationRefAttributeRemovedEvent, and RepresentationRefAttributeUpdatedEvent. Consequently, an infinite loop occurs between SCIMRepresentationAttribute and SCIMRepresentation.

I will ignore the Representation attached to the SCIMRepresentationAttribute :)

I have sent you an invitation to become a collaborator

**Comment by danflomin** [comment]
Thank you very much!

**Comment by danflomin** [comment]
Hello

I pushed an improvement to release/4.0.2.
I need this for my application.

Is that OK?

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

Sorry for my late reply, i'm ok with your changes :)

KR,

SID
