### ISSUE TITLE
[SCIM] Error on GET Groups / Users using the filter by id 4.0.4

### ISSUE THREAD

**Issue by polybogdan** [simpleidserver/SimpleIdServer#596]
Hello,

I'm facing getting an error when filtering by id in groups and users:

![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/c3fc7730-143d-480f-86c4-3630c235778b)

I know it can be bypassed by calling the /Groups/1dc38a35-e4a2-4d7c-8940-c204db0cf3e8 yet an application that currently uses the SCIM doing call by passing multiple id es:
/Groups?filter=id eq "1dc38a35-e4a2-4d7c-8940-c204db0cf3e8" or id "7a704f9c-bb1b-4ca9-ba48-aed1c7ea7d70"

**Comment by simpleidserver** [comment]
Hello,

Due to the modifications made in the release "4.0.4" to improve the performance of the SCIM project, there are some unexpected regressions :(

The issue has been fixed in the branch "release/4.0.5" :)

If you notice any other regressions, please don't hesitate to create bug tickets.

Best regards,

SID

**Comment by polybogdan** [comment]
Hello,

With the 4.0.5 the issue seems to be fixed:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/2445870/4e51d4dd-49f9-493a-8021-919e0cfb8a78)

BR 

Bogdan
