### ISSUE TITLE
[SCIM] PATCH replace operation remove others properties

### ISSUE THREAD

**Issue by gabrielemilan** [simpleidserver/SimpleIdServer#715]
Hello, it seems there is a regression in the replace operation.

![image](https://github.com/simpleidserver/SimpleIdServer/assets/10979448/bf40944a-9df5-4e0c-ad76-eff8a0b3979d)

Some arrays have been deleted.

Can you please check?
Regards.

**Comment by simpleidserver** [comment]
Hello,

Due to performance issues, we have made some modifications to the SimpleIdServer.Scim package. Now, it does not return the entire object or representation in the response to an **HTTP PATCH or PUT** request.

There are scenarios where a user can be assigned to more than one million groups. In such situations, we do not wish to return the full representation.

Could you please check if the representation is correct when you execute an **HTTP GET**?

If you prefer, we can add a new property, `IsFullRepresentationReturned`, in the options. This property would enable returning the full representation in the response when set to true.

Best regards,

SID

**Comment by gabrielemilan** [comment]
Yes please, it can be a good solution.

Thanks

**Comment by simpleidserver** [comment]
The 'IsFullRepresentationReturned' property has been added to the options. When this property is set to true, the full representation will be returned.

**Comment by gabrielemilan** [comment]
> The 'IsFullRepresentationReturned' property has been added to the options. When this property is set to true, the full representation will be returned.

Ok thanks, is it the version already published?

**Comment by simpleidserver** [comment]
The version has not yet been published. I will release a pre-release version next week.
