### ISSUE TITLE
Required attribute does not work correctly in SCIM schema description 

### ISSUE THREAD

**Issue by sw-kosaki** [simpleidserver/SimpleIdServer#74]
Hello,
we found that 'required' attribute used in SCIM schema elements does not work correctly - if this one is set on 'true' and relevant fields missing in the coming ScimRepresentation data - nothing happens and code which consumes this data continues its execution unimpeded.

**Examle:**

.AddComplexAttribute("name", c =>
                    {
                        c.AddStringAttribute("familyName", description: "The family name", **required**: true);
                        c.AddStringAttribute("givenName", description: "The given name", **required**: true);
                    },

Thank you in advance.

**Comment by simpleidserver** [comment]
Hi,

In the configuration don't forget to pass "required:true" in "AddComplexAttribute("name")" method. You must have the following configuration :

.AddComplexAttribute("name", c =>
{
c.AddStringAttribute("familyName", description: "The family name", required: true);
c.AddStringAttribute("givenName", description: "The given name", required: true);
}, required: true)

The validation of sub attributes was missing, it has been included in the branch "release/1.2.0" & some UTS have been added in order to check the validation rules.

**Comment by sw-kosaki** [comment]
Thank you for this quick fix!
