### ISSUE TITLE
Encounter problems

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#760]
Hello, excuse me. I downloaded your latest master project, and when I bind webauth to the user in the 5001 page, 5001 reports an error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/577b1195-1aec-44e6-9f1c-8e9dddb9a6d2)
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/1d857b6c-0722-4ce0-8faf-2dfa18638195)

**Comment by qq1176914912** [comment]
Hello, when using LDAP, if my ldap server does not set The group information, an error message is displayed: The object does not exist.. I looked at the source code: now it looks like you have to add a group, so I'll use a try catch to get the user. I don't know if I'm doing the right thing.
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/b20a7ff1-7495-4a7a-b09e-634796ab1fa4)

**Comment by qq1176914912** [comment]
After importing through LDAP, when I want to view users through user management, a problem occurs:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/55ff65cf-77a8-4cb7-a84c-bf112d3ae3b9)
I checked the database and found that the account was created when:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/77fed564-3d5b-47a6-9b0f-35865b23db84)
Is this creation time to get the LDAP server?
I am using a postgresql database.

**Comment by simpleidserver** [comment]
Hello,

**Webauthn**

An exception was thrown because the MobileOptions and WebauthnOptions options did not implement the IFidoOptions interface. This issue is fixed in the master branch.

**LDAP Group**

A new property, IsGroupSyncEnabled, has been added to the LDAPRepresentationsExtractionJobOptions class. When this property is false, the groups will not be synchronized.

**CreateDateTime Invalid**

The CreateDateTime was not properly set. This issue is fixed in the master branch.
